#!/bin/sh

src=$(dirname $0)

if [ "$(readlink -f $src)" = "$(readlink -f .)" ]; then
    echo "self"
    exit 1
fi

ln $src/aliases .aliases
ln $src/bash_profile .bash_profile
ln $src/bashrc .bashrc
ln $src/clang-format .clang-format
ln $src/colordiffrc .colordiffrc
ln $src/colorgccrc .colorgccrc
ln $src/dir_colors .dir_colors
ln $src/git/config .gitconfig
ln $src/git/ignore .gitignore
ln $src/inputrc .inputrc
ln $src/profile .profile
ln $src/radiorc .radiorc
ln $src/screenrc .screenrc
[ -L .vim ] || ln -s $src/vim .vim
ln $src/vimrc .vimrc

if [ -d .bash_completion.d ]; then
    ln $src/bash_completion.d/radio .bash_completion.d/
fi

if [ -d bin ]; then
    ln $src/bin/perror bin/
    ln $src/bin/radio bin/
fi
