tap "homebrew/cask-cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"

brew "cmake"
brew "doxygen"
brew "gcc"
brew "git"
brew "lcov"
brew "ninja"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD", "without-docutils", "without-xml"]
brew "zsh"
brew "zsh-completions"

cask "iterm2"
cask "mpv"
cask "transmission"

#tap "svens/home", "https://github.com/svens/home"
#brew "svens/home/vim"
